import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { Rings } from "react-loader-spinner";

import UseSearch from "../hooks/useSearch";
import styles from "../styles/Home.module.scss";
import DisplayResults from "../components/DisplayResults";

const Home = () => {
  const {
    video,
    results,
    search,
    handleChange,
    fetchData,
    loading,
  } = UseSearch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Ethereal Scanner</h1>
        <p className={styles.text}>Enter a Tik Tok URL and get results for the related songs and hastags used in the video</p>
        <p className={styles.text}>Click a tag when it appears to show results. Hover over a video to play</p>

        <input
          onChange={(e) => handleChange(e)}
          className={styles.input}
          type="text"
        />
        <button className={styles.colorChange}onClick={fetchData}>Scan</button>
        {loading ? (
          <Rings color="#00BFFF" height={80} width={80} />
        ) : (
          <DisplayResults
            results={results}
            video={video}
          />
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.etherealkind.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Ethereal
          <span className={styles.logo}></span>
          {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
        </a>
      </footer>
    </div>
  );
};

export default Home;
